### ISSUE TITLE
Failed transaction for multiple stores

### ISSUE THREAD

**Issue by ph-fritsche** [jakearchibald/idb-keyval#101]
Using multiple stores in the same database per `createStore()` fails because subsequent stores are not created.

```js
import {createStore, set} from 'idb-keyval'

async function demo() {
  const storeA = createStore('demoDB', 'storeA') // this works
  const storeB = createStore('demoDB', 'storeB') // this does nothing
  await set('entryA', 'valueA', storeA) // this works
  await set('entryB', 'valueB', storeB) // this throws NotFoundError
}
demo()
```

See: https://codesandbox.io/s/strange-blackburn-q34e2

**Comment by joaoml** [comment]
I was trying to implement similar behavior today and I was facing this same issue. 

After doing some investigation the issue seems to be in the way that `createObjectStore` is being called in https://github.com/jakearchibald/idb-keyval/blob/master/src/index.ts#L14
```typescript
  request.onupgradeneeded = () => request.result.createObjectStore(storeName);
```
> The onupgradeneeded property of the IDBOpenDBRequest interface is the event handler for the upgradeneeded event, triggered when a database of a bigger version number than the existing stored database is loaded.

Following the demo provided by @ph-fritsche,  that's why only `storeA` is created and added to `objectStoreNames`. `objectStoreNames` will only contain a single entry corresponding to `storeA`. When you try to `set` into `storeB`, the transaction error is thrown because this store does not exist in `objectStoreNames`.

I'm wondering if a possible solution can be: check if `storeName` does not exist in the database and then call `request.result.createObjectStore(storeName);`

-----
Thanks for effort in this library 🙌

**Comment by ph-fritsche** [comment]
Could [this](https://github.com/ph-fritsche/idb-keyval/commit/08d6bb3e952588e5e30d92e262930421bb6015ab) be a solution?

(There is no automated test and the rollup config does not yield a `dist` on my machine. Before I set up another test environment maybe someone could check this.)

**Comment by ph-fritsche** [comment]
Updated [fix-101](https://github.com/ph-fritsche/idb-keyval/tree/fix-101). Thanks to @joaoml

**Comment by joaoml** [comment]
I was trying the possible solution while reading the documentation and is probably more complicated. `createObjectStore` can only be called in the `onupgradeneeded` event. 

To add a 2nd store, the event need to be triggered again and seems to be only possible when database is created or version increased

**Comment by ph-fritsche** [comment]
Updated [fix-101](https://github.com/jakearchibald/idb-keyval/compare/master...ph-fritsche:fix-101)
Moved the `createObjectStore` call back into the `onupgradeneeded` event handler.
It checks if the store exists and opens the database again with a new version if it does not.

**Comment by joaoml** [comment]
> But createStore won't let you create multiple stores within the same database. Nor will it let you create a store within an existing database.

https://github.com/jakearchibald/idb-keyval/blob/master/custom-stores.md 

This behavior is already identified 😅  this issue is expected

**Comment by ph-fritsche** [comment]
I'll leave this open as we might already have a fix. Maybe it will be merged as a new feature if it works

**Comment by jakearchibald** [comment]
Yeah, https://github.com/jakearchibald/idb-keyval/blob/master/custom-stores.md#defining-a-custom-database--store-name details the limitations of this API, and the workarounds if you want to do something more involved.
